package com.oliveoa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oliveoa.pojo.AnnouncementApprovedOpinionList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANNOUNCEMENT_APPROVED_OPINION_LIST".
*/
public class AnnouncementApprovedOpinionListDao extends AbstractDao<AnnouncementApprovedOpinionList, Void> {

    public static final String TABLENAME = "ANNOUNCEMENT_APPROVED_OPINION_LIST";

    /**
     * Properties of entity AnnouncementApprovedOpinionList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Aaocid = new Property(0, String.class, "aaocid", false, "AAOCID");
        public final static Property Aaopid = new Property(1, String.class, "aaopid", false, "AAOPID");
        public final static Property Aid = new Property(2, String.class, "aid", false, "AID");
        public final static Property Eid = new Property(3, String.class, "eid", false, "EID");
        public final static Property Isapproved = new Property(4, int.class, "isapproved", false, "ISAPPROVED");
        public final static Property Opinion = new Property(5, String.class, "opinion", false, "OPINION");
        public final static Property Orderby = new Property(6, int.class, "orderby", false, "ORDERBY");
        public final static Property Createtime = new Property(7, long.class, "createtime", false, "CREATETIME");
        public final static Property Updatetime = new Property(8, long.class, "updatetime", false, "UPDATETIME");
    }


    public AnnouncementApprovedOpinionListDao(DaoConfig config) {
        super(config);
    }
    
    public AnnouncementApprovedOpinionListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANNOUNCEMENT_APPROVED_OPINION_LIST\" (" + //
                "\"AAOCID\" TEXT," + // 0: aaocid
                "\"AAOPID\" TEXT," + // 1: aaopid
                "\"AID\" TEXT," + // 2: aid
                "\"EID\" TEXT," + // 3: eid
                "\"ISAPPROVED\" INTEGER NOT NULL ," + // 4: isapproved
                "\"OPINION\" TEXT," + // 5: opinion
                "\"ORDERBY\" INTEGER NOT NULL ," + // 6: orderby
                "\"CREATETIME\" INTEGER NOT NULL ," + // 7: createtime
                "\"UPDATETIME\" INTEGER NOT NULL );"); // 8: updatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANNOUNCEMENT_APPROVED_OPINION_LIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AnnouncementApprovedOpinionList entity) {
        stmt.clearBindings();
 
        String aaocid = entity.getAaocid();
        if (aaocid != null) {
            stmt.bindString(1, aaocid);
        }
 
        String aaopid = entity.getAaopid();
        if (aaopid != null) {
            stmt.bindString(2, aaopid);
        }
 
        String aid = entity.getAid();
        if (aid != null) {
            stmt.bindString(3, aid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(4, eid);
        }
        stmt.bindLong(5, entity.getIsapproved());
 
        String opinion = entity.getOpinion();
        if (opinion != null) {
            stmt.bindString(6, opinion);
        }
        stmt.bindLong(7, entity.getOrderby());
        stmt.bindLong(8, entity.getCreatetime());
        stmt.bindLong(9, entity.getUpdatetime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AnnouncementApprovedOpinionList entity) {
        stmt.clearBindings();
 
        String aaocid = entity.getAaocid();
        if (aaocid != null) {
            stmt.bindString(1, aaocid);
        }
 
        String aaopid = entity.getAaopid();
        if (aaopid != null) {
            stmt.bindString(2, aaopid);
        }
 
        String aid = entity.getAid();
        if (aid != null) {
            stmt.bindString(3, aid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(4, eid);
        }
        stmt.bindLong(5, entity.getIsapproved());
 
        String opinion = entity.getOpinion();
        if (opinion != null) {
            stmt.bindString(6, opinion);
        }
        stmt.bindLong(7, entity.getOrderby());
        stmt.bindLong(8, entity.getCreatetime());
        stmt.bindLong(9, entity.getUpdatetime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public AnnouncementApprovedOpinionList readEntity(Cursor cursor, int offset) {
        AnnouncementApprovedOpinionList entity = new AnnouncementApprovedOpinionList( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // aaocid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // aaopid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // aid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // eid
            cursor.getInt(offset + 4), // isapproved
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // opinion
            cursor.getInt(offset + 6), // orderby
            cursor.getLong(offset + 7), // createtime
            cursor.getLong(offset + 8) // updatetime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AnnouncementApprovedOpinionList entity, int offset) {
        entity.setAaocid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAaopid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsapproved(cursor.getInt(offset + 4));
        entity.setOpinion(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOrderby(cursor.getInt(offset + 6));
        entity.setCreatetime(cursor.getLong(offset + 7));
        entity.setUpdatetime(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(AnnouncementApprovedOpinionList entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(AnnouncementApprovedOpinionList entity) {
        return null;
    }

    @Override
    public boolean hasKey(AnnouncementApprovedOpinionList entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
