package com.oliveoa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oliveoa.pojo.Application;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APPLICATION".
*/
public class ApplicationDao extends AbstractDao<Application, Void> {

    public static final String TABLENAME = "APPLICATION";

    /**
     * Properties of entity Application.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Describe = new Property(0, String.class, "describe", false, "DESCRIBE");
        public final static Property Aid = new Property(1, String.class, "aid", false, "AID");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Status = new Property(3, int.class, "status", false, "STATUS");
    }


    public ApplicationDao(DaoConfig config) {
        super(config);
    }
    
    public ApplicationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APPLICATION\" (" + //
                "\"DESCRIBE\" TEXT," + // 0: describe
                "\"AID\" TEXT," + // 1: aid
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"STATUS\" INTEGER NOT NULL );"); // 3: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APPLICATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Application entity) {
        stmt.clearBindings();
 
        String describe = entity.getDescribe();
        if (describe != null) {
            stmt.bindString(1, describe);
        }
 
        String aid = entity.getAid();
        if (aid != null) {
            stmt.bindString(2, aid);
        }
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Application entity) {
        stmt.clearBindings();
 
        String describe = entity.getDescribe();
        if (describe != null) {
            stmt.bindString(1, describe);
        }
 
        String aid = entity.getAid();
        if (aid != null) {
            stmt.bindString(2, aid);
        }
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getStatus());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Application readEntity(Cursor cursor, int offset) {
        Application entity = new Application( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // describe
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // aid
            cursor.getInt(offset + 2), // type
            cursor.getInt(offset + 3) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Application entity, int offset) {
        entity.setDescribe(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setStatus(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Application entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Application entity) {
        return null;
    }

    @Override
    public boolean hasKey(Application entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
