package com.oliveoa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oliveoa.pojo.BusinessTripApplicationApprovedOpinionList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BUSINESS_TRIP_APPLICATION_APPROVED_OPINION_LIST".
*/
public class BusinessTripApplicationApprovedOpinionListDao extends AbstractDao<BusinessTripApplicationApprovedOpinionList, Void> {

    public static final String TABLENAME = "BUSINESS_TRIP_APPLICATION_APPROVED_OPINION_LIST";

    /**
     * Properties of entity BusinessTripApplicationApprovedOpinionList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Btaaocid = new Property(0, String.class, "btaaocid", false, "BTAAOCID");
        public final static Property Btaaopid = new Property(1, String.class, "btaaopid", false, "BTAAOPID");
        public final static Property Btaid = new Property(2, String.class, "btaid", false, "BTAID");
        public final static Property Eid = new Property(3, String.class, "eid", false, "EID");
        public final static Property Isapproved = new Property(4, int.class, "isapproved", false, "ISAPPROVED");
        public final static Property Opinion = new Property(5, String.class, "opinion", false, "OPINION");
        public final static Property Orderby = new Property(6, int.class, "orderby", false, "ORDERBY");
        public final static Property Createtime = new Property(7, long.class, "createtime", false, "CREATETIME");
        public final static Property Updatetime = new Property(8, long.class, "updatetime", false, "UPDATETIME");
    }


    public BusinessTripApplicationApprovedOpinionListDao(DaoConfig config) {
        super(config);
    }
    
    public BusinessTripApplicationApprovedOpinionListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BUSINESS_TRIP_APPLICATION_APPROVED_OPINION_LIST\" (" + //
                "\"BTAAOCID\" TEXT," + // 0: btaaocid
                "\"BTAAOPID\" TEXT," + // 1: btaaopid
                "\"BTAID\" TEXT," + // 2: btaid
                "\"EID\" TEXT," + // 3: eid
                "\"ISAPPROVED\" INTEGER NOT NULL ," + // 4: isapproved
                "\"OPINION\" TEXT," + // 5: opinion
                "\"ORDERBY\" INTEGER NOT NULL ," + // 6: orderby
                "\"CREATETIME\" INTEGER NOT NULL ," + // 7: createtime
                "\"UPDATETIME\" INTEGER NOT NULL );"); // 8: updatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BUSINESS_TRIP_APPLICATION_APPROVED_OPINION_LIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BusinessTripApplicationApprovedOpinionList entity) {
        stmt.clearBindings();
 
        String btaaocid = entity.getBtaaocid();
        if (btaaocid != null) {
            stmt.bindString(1, btaaocid);
        }
 
        String btaaopid = entity.getBtaaopid();
        if (btaaopid != null) {
            stmt.bindString(2, btaaopid);
        }
 
        String btaid = entity.getBtaid();
        if (btaid != null) {
            stmt.bindString(3, btaid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(4, eid);
        }
        stmt.bindLong(5, entity.getIsapproved());
 
        String opinion = entity.getOpinion();
        if (opinion != null) {
            stmt.bindString(6, opinion);
        }
        stmt.bindLong(7, entity.getOrderby());
        stmt.bindLong(8, entity.getCreatetime());
        stmt.bindLong(9, entity.getUpdatetime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BusinessTripApplicationApprovedOpinionList entity) {
        stmt.clearBindings();
 
        String btaaocid = entity.getBtaaocid();
        if (btaaocid != null) {
            stmt.bindString(1, btaaocid);
        }
 
        String btaaopid = entity.getBtaaopid();
        if (btaaopid != null) {
            stmt.bindString(2, btaaopid);
        }
 
        String btaid = entity.getBtaid();
        if (btaid != null) {
            stmt.bindString(3, btaid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(4, eid);
        }
        stmt.bindLong(5, entity.getIsapproved());
 
        String opinion = entity.getOpinion();
        if (opinion != null) {
            stmt.bindString(6, opinion);
        }
        stmt.bindLong(7, entity.getOrderby());
        stmt.bindLong(8, entity.getCreatetime());
        stmt.bindLong(9, entity.getUpdatetime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public BusinessTripApplicationApprovedOpinionList readEntity(Cursor cursor, int offset) {
        BusinessTripApplicationApprovedOpinionList entity = new BusinessTripApplicationApprovedOpinionList( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // btaaocid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // btaaopid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // btaid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // eid
            cursor.getInt(offset + 4), // isapproved
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // opinion
            cursor.getInt(offset + 6), // orderby
            cursor.getLong(offset + 7), // createtime
            cursor.getLong(offset + 8) // updatetime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BusinessTripApplicationApprovedOpinionList entity, int offset) {
        entity.setBtaaocid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setBtaaopid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBtaid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsapproved(cursor.getInt(offset + 4));
        entity.setOpinion(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOrderby(cursor.getInt(offset + 6));
        entity.setCreatetime(cursor.getLong(offset + 7));
        entity.setUpdatetime(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(BusinessTripApplicationApprovedOpinionList entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(BusinessTripApplicationApprovedOpinionList entity) {
        return null;
    }

    @Override
    public boolean hasKey(BusinessTripApplicationApprovedOpinionList entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
