package com.oliveoa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oliveoa.pojo.BusinessTripApplication;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BUSINESS_TRIP_APPLICATION".
*/
public class BusinessTripApplicationDao extends AbstractDao<BusinessTripApplication, Void> {

    public static final String TABLENAME = "BUSINESS_TRIP_APPLICATION";

    /**
     * Properties of entity BusinessTripApplication.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Btaid = new Property(0, String.class, "btaid", false, "BTAID");
        public final static Property Eid = new Property(1, String.class, "eid", false, "EID");
        public final static Property Begintime = new Property(2, long.class, "begintime", false, "BEGINTIME");
        public final static Property Endtime = new Property(3, long.class, "endtime", false, "ENDTIME");
        public final static Property Place = new Property(4, String.class, "place", false, "PLACE");
        public final static Property Task = new Property(5, String.class, "task", false, "TASK");
        public final static Property Orderby = new Property(6, int.class, "orderby", false, "ORDERBY");
        public final static Property Createime = new Property(7, long.class, "createime", false, "CREATEIME");
        public final static Property Updatetime = new Property(8, long.class, "updatetime", false, "UPDATETIME");
    }


    public BusinessTripApplicationDao(DaoConfig config) {
        super(config);
    }
    
    public BusinessTripApplicationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BUSINESS_TRIP_APPLICATION\" (" + //
                "\"BTAID\" TEXT," + // 0: btaid
                "\"EID\" TEXT," + // 1: eid
                "\"BEGINTIME\" INTEGER NOT NULL ," + // 2: begintime
                "\"ENDTIME\" INTEGER NOT NULL ," + // 3: endtime
                "\"PLACE\" TEXT," + // 4: place
                "\"TASK\" TEXT," + // 5: task
                "\"ORDERBY\" INTEGER NOT NULL ," + // 6: orderby
                "\"CREATEIME\" INTEGER NOT NULL ," + // 7: createime
                "\"UPDATETIME\" INTEGER NOT NULL );"); // 8: updatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BUSINESS_TRIP_APPLICATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BusinessTripApplication entity) {
        stmt.clearBindings();
 
        String btaid = entity.getBtaid();
        if (btaid != null) {
            stmt.bindString(1, btaid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(2, eid);
        }
        stmt.bindLong(3, entity.getBegintime());
        stmt.bindLong(4, entity.getEndtime());
 
        String place = entity.getPlace();
        if (place != null) {
            stmt.bindString(5, place);
        }
 
        String task = entity.getTask();
        if (task != null) {
            stmt.bindString(6, task);
        }
        stmt.bindLong(7, entity.getOrderby());
        stmt.bindLong(8, entity.getCreateime());
        stmt.bindLong(9, entity.getUpdatetime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BusinessTripApplication entity) {
        stmt.clearBindings();
 
        String btaid = entity.getBtaid();
        if (btaid != null) {
            stmt.bindString(1, btaid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(2, eid);
        }
        stmt.bindLong(3, entity.getBegintime());
        stmt.bindLong(4, entity.getEndtime());
 
        String place = entity.getPlace();
        if (place != null) {
            stmt.bindString(5, place);
        }
 
        String task = entity.getTask();
        if (task != null) {
            stmt.bindString(6, task);
        }
        stmt.bindLong(7, entity.getOrderby());
        stmt.bindLong(8, entity.getCreateime());
        stmt.bindLong(9, entity.getUpdatetime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public BusinessTripApplication readEntity(Cursor cursor, int offset) {
        BusinessTripApplication entity = new BusinessTripApplication( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // btaid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // eid
            cursor.getLong(offset + 2), // begintime
            cursor.getLong(offset + 3), // endtime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // place
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // task
            cursor.getInt(offset + 6), // orderby
            cursor.getLong(offset + 7), // createime
            cursor.getLong(offset + 8) // updatetime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BusinessTripApplication entity, int offset) {
        entity.setBtaid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setEid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBegintime(cursor.getLong(offset + 2));
        entity.setEndtime(cursor.getLong(offset + 3));
        entity.setPlace(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTask(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOrderby(cursor.getInt(offset + 6));
        entity.setCreateime(cursor.getLong(offset + 7));
        entity.setUpdatetime(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(BusinessTripApplication entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(BusinessTripApplication entity) {
        return null;
    }

    @Override
    public boolean hasKey(BusinessTripApplication entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
