package com.oliveoa.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.oliveoa.pojo.AnnouncementApprovedOpinionList;
import com.oliveoa.pojo.AnnouncementInfo;
import com.oliveoa.pojo.Application;
import com.oliveoa.pojo.BusinessTripApplication;
import com.oliveoa.pojo.BusinessTripApplicationApprovedOpinionList;
import com.oliveoa.pojo.ContactInfo;
import com.oliveoa.pojo.DepartmentInfo;
import com.oliveoa.pojo.DutyInfo;
import com.oliveoa.pojo.IssueWork;
import com.oliveoa.pojo.LeaveApplication;
import com.oliveoa.pojo.LeaveApplicationApprovedOpinionList;
import com.oliveoa.pojo.Message;
import com.oliveoa.pojo.OvertimeApplication;
import com.oliveoa.pojo.OvertimeApplicationApprovedOpinionList;
import com.oliveoa.pojo.UserLoginInfo;
import com.oliveoa.pojo.WorkDetail;

import com.oliveoa.greendao.AnnouncementApprovedOpinionListDao;
import com.oliveoa.greendao.AnnouncementInfoDao;
import com.oliveoa.greendao.ApplicationDao;
import com.oliveoa.greendao.BusinessTripApplicationDao;
import com.oliveoa.greendao.BusinessTripApplicationApprovedOpinionListDao;
import com.oliveoa.greendao.ContactInfoDao;
import com.oliveoa.greendao.DepartmentInfoDao;
import com.oliveoa.greendao.DutyInfoDao;
import com.oliveoa.greendao.IssueWorkDao;
import com.oliveoa.greendao.LeaveApplicationDao;
import com.oliveoa.greendao.LeaveApplicationApprovedOpinionListDao;
import com.oliveoa.greendao.MessageDao;
import com.oliveoa.greendao.OvertimeApplicationDao;
import com.oliveoa.greendao.OvertimeApplicationApprovedOpinionListDao;
import com.oliveoa.greendao.UserLoginInfoDao;
import com.oliveoa.greendao.WorkDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig announcementApprovedOpinionListDaoConfig;
    private final DaoConfig announcementInfoDaoConfig;
    private final DaoConfig applicationDaoConfig;
    private final DaoConfig businessTripApplicationDaoConfig;
    private final DaoConfig businessTripApplicationApprovedOpinionListDaoConfig;
    private final DaoConfig contactInfoDaoConfig;
    private final DaoConfig departmentInfoDaoConfig;
    private final DaoConfig dutyInfoDaoConfig;
    private final DaoConfig issueWorkDaoConfig;
    private final DaoConfig leaveApplicationDaoConfig;
    private final DaoConfig leaveApplicationApprovedOpinionListDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig overtimeApplicationDaoConfig;
    private final DaoConfig overtimeApplicationApprovedOpinionListDaoConfig;
    private final DaoConfig userLoginInfoDaoConfig;
    private final DaoConfig workDetailDaoConfig;

    private final AnnouncementApprovedOpinionListDao announcementApprovedOpinionListDao;
    private final AnnouncementInfoDao announcementInfoDao;
    private final ApplicationDao applicationDao;
    private final BusinessTripApplicationDao businessTripApplicationDao;
    private final BusinessTripApplicationApprovedOpinionListDao businessTripApplicationApprovedOpinionListDao;
    private final ContactInfoDao contactInfoDao;
    private final DepartmentInfoDao departmentInfoDao;
    private final DutyInfoDao dutyInfoDao;
    private final IssueWorkDao issueWorkDao;
    private final LeaveApplicationDao leaveApplicationDao;
    private final LeaveApplicationApprovedOpinionListDao leaveApplicationApprovedOpinionListDao;
    private final MessageDao messageDao;
    private final OvertimeApplicationDao overtimeApplicationDao;
    private final OvertimeApplicationApprovedOpinionListDao overtimeApplicationApprovedOpinionListDao;
    private final UserLoginInfoDao userLoginInfoDao;
    private final WorkDetailDao workDetailDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        announcementApprovedOpinionListDaoConfig = daoConfigMap.get(AnnouncementApprovedOpinionListDao.class).clone();
        announcementApprovedOpinionListDaoConfig.initIdentityScope(type);

        announcementInfoDaoConfig = daoConfigMap.get(AnnouncementInfoDao.class).clone();
        announcementInfoDaoConfig.initIdentityScope(type);

        applicationDaoConfig = daoConfigMap.get(ApplicationDao.class).clone();
        applicationDaoConfig.initIdentityScope(type);

        businessTripApplicationDaoConfig = daoConfigMap.get(BusinessTripApplicationDao.class).clone();
        businessTripApplicationDaoConfig.initIdentityScope(type);

        businessTripApplicationApprovedOpinionListDaoConfig = daoConfigMap.get(BusinessTripApplicationApprovedOpinionListDao.class).clone();
        businessTripApplicationApprovedOpinionListDaoConfig.initIdentityScope(type);

        contactInfoDaoConfig = daoConfigMap.get(ContactInfoDao.class).clone();
        contactInfoDaoConfig.initIdentityScope(type);

        departmentInfoDaoConfig = daoConfigMap.get(DepartmentInfoDao.class).clone();
        departmentInfoDaoConfig.initIdentityScope(type);

        dutyInfoDaoConfig = daoConfigMap.get(DutyInfoDao.class).clone();
        dutyInfoDaoConfig.initIdentityScope(type);

        issueWorkDaoConfig = daoConfigMap.get(IssueWorkDao.class).clone();
        issueWorkDaoConfig.initIdentityScope(type);

        leaveApplicationDaoConfig = daoConfigMap.get(LeaveApplicationDao.class).clone();
        leaveApplicationDaoConfig.initIdentityScope(type);

        leaveApplicationApprovedOpinionListDaoConfig = daoConfigMap.get(LeaveApplicationApprovedOpinionListDao.class).clone();
        leaveApplicationApprovedOpinionListDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        overtimeApplicationDaoConfig = daoConfigMap.get(OvertimeApplicationDao.class).clone();
        overtimeApplicationDaoConfig.initIdentityScope(type);

        overtimeApplicationApprovedOpinionListDaoConfig = daoConfigMap.get(OvertimeApplicationApprovedOpinionListDao.class).clone();
        overtimeApplicationApprovedOpinionListDaoConfig.initIdentityScope(type);

        userLoginInfoDaoConfig = daoConfigMap.get(UserLoginInfoDao.class).clone();
        userLoginInfoDaoConfig.initIdentityScope(type);

        workDetailDaoConfig = daoConfigMap.get(WorkDetailDao.class).clone();
        workDetailDaoConfig.initIdentityScope(type);

        announcementApprovedOpinionListDao = new AnnouncementApprovedOpinionListDao(announcementApprovedOpinionListDaoConfig, this);
        announcementInfoDao = new AnnouncementInfoDao(announcementInfoDaoConfig, this);
        applicationDao = new ApplicationDao(applicationDaoConfig, this);
        businessTripApplicationDao = new BusinessTripApplicationDao(businessTripApplicationDaoConfig, this);
        businessTripApplicationApprovedOpinionListDao = new BusinessTripApplicationApprovedOpinionListDao(businessTripApplicationApprovedOpinionListDaoConfig, this);
        contactInfoDao = new ContactInfoDao(contactInfoDaoConfig, this);
        departmentInfoDao = new DepartmentInfoDao(departmentInfoDaoConfig, this);
        dutyInfoDao = new DutyInfoDao(dutyInfoDaoConfig, this);
        issueWorkDao = new IssueWorkDao(issueWorkDaoConfig, this);
        leaveApplicationDao = new LeaveApplicationDao(leaveApplicationDaoConfig, this);
        leaveApplicationApprovedOpinionListDao = new LeaveApplicationApprovedOpinionListDao(leaveApplicationApprovedOpinionListDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        overtimeApplicationDao = new OvertimeApplicationDao(overtimeApplicationDaoConfig, this);
        overtimeApplicationApprovedOpinionListDao = new OvertimeApplicationApprovedOpinionListDao(overtimeApplicationApprovedOpinionListDaoConfig, this);
        userLoginInfoDao = new UserLoginInfoDao(userLoginInfoDaoConfig, this);
        workDetailDao = new WorkDetailDao(workDetailDaoConfig, this);

        registerDao(AnnouncementApprovedOpinionList.class, announcementApprovedOpinionListDao);
        registerDao(AnnouncementInfo.class, announcementInfoDao);
        registerDao(Application.class, applicationDao);
        registerDao(BusinessTripApplication.class, businessTripApplicationDao);
        registerDao(BusinessTripApplicationApprovedOpinionList.class, businessTripApplicationApprovedOpinionListDao);
        registerDao(ContactInfo.class, contactInfoDao);
        registerDao(DepartmentInfo.class, departmentInfoDao);
        registerDao(DutyInfo.class, dutyInfoDao);
        registerDao(IssueWork.class, issueWorkDao);
        registerDao(LeaveApplication.class, leaveApplicationDao);
        registerDao(LeaveApplicationApprovedOpinionList.class, leaveApplicationApprovedOpinionListDao);
        registerDao(Message.class, messageDao);
        registerDao(OvertimeApplication.class, overtimeApplicationDao);
        registerDao(OvertimeApplicationApprovedOpinionList.class, overtimeApplicationApprovedOpinionListDao);
        registerDao(UserLoginInfo.class, userLoginInfoDao);
        registerDao(WorkDetail.class, workDetailDao);
    }
    
    public void clear() {
        announcementApprovedOpinionListDaoConfig.clearIdentityScope();
        announcementInfoDaoConfig.clearIdentityScope();
        applicationDaoConfig.clearIdentityScope();
        businessTripApplicationDaoConfig.clearIdentityScope();
        businessTripApplicationApprovedOpinionListDaoConfig.clearIdentityScope();
        contactInfoDaoConfig.clearIdentityScope();
        departmentInfoDaoConfig.clearIdentityScope();
        dutyInfoDaoConfig.clearIdentityScope();
        issueWorkDaoConfig.clearIdentityScope();
        leaveApplicationDaoConfig.clearIdentityScope();
        leaveApplicationApprovedOpinionListDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        overtimeApplicationDaoConfig.clearIdentityScope();
        overtimeApplicationApprovedOpinionListDaoConfig.clearIdentityScope();
        userLoginInfoDaoConfig.clearIdentityScope();
        workDetailDaoConfig.clearIdentityScope();
    }

    public AnnouncementApprovedOpinionListDao getAnnouncementApprovedOpinionListDao() {
        return announcementApprovedOpinionListDao;
    }

    public AnnouncementInfoDao getAnnouncementInfoDao() {
        return announcementInfoDao;
    }

    public ApplicationDao getApplicationDao() {
        return applicationDao;
    }

    public BusinessTripApplicationDao getBusinessTripApplicationDao() {
        return businessTripApplicationDao;
    }

    public BusinessTripApplicationApprovedOpinionListDao getBusinessTripApplicationApprovedOpinionListDao() {
        return businessTripApplicationApprovedOpinionListDao;
    }

    public ContactInfoDao getContactInfoDao() {
        return contactInfoDao;
    }

    public DepartmentInfoDao getDepartmentInfoDao() {
        return departmentInfoDao;
    }

    public DutyInfoDao getDutyInfoDao() {
        return dutyInfoDao;
    }

    public IssueWorkDao getIssueWorkDao() {
        return issueWorkDao;
    }

    public LeaveApplicationDao getLeaveApplicationDao() {
        return leaveApplicationDao;
    }

    public LeaveApplicationApprovedOpinionListDao getLeaveApplicationApprovedOpinionListDao() {
        return leaveApplicationApprovedOpinionListDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public OvertimeApplicationDao getOvertimeApplicationDao() {
        return overtimeApplicationDao;
    }

    public OvertimeApplicationApprovedOpinionListDao getOvertimeApplicationApprovedOpinionListDao() {
        return overtimeApplicationApprovedOpinionListDao;
    }

    public UserLoginInfoDao getUserLoginInfoDao() {
        return userLoginInfoDao;
    }

    public WorkDetailDao getWorkDetailDao() {
        return workDetailDao;
    }

}
