package com.oliveoa.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.oliveoa.pojo.AnnouncementApprovedOpinionList;
import com.oliveoa.pojo.AnnouncementInfo;
import com.oliveoa.pojo.Application;
import com.oliveoa.pojo.BusinessTripApplication;
import com.oliveoa.pojo.BusinessTripApplicationApprovedOpinionList;
import com.oliveoa.pojo.ContactInfo;
import com.oliveoa.pojo.DepartmentInfo;
import com.oliveoa.pojo.DutyInfo;
import com.oliveoa.pojo.IssueWork;
import com.oliveoa.pojo.LeaveApplication;
import com.oliveoa.pojo.LeaveApplicationApprovedOpinionList;
import com.oliveoa.pojo.Message;
import com.oliveoa.pojo.OvertimeApplication;
import com.oliveoa.pojo.OvertimeApplicationApprovedOpinionList;
import com.oliveoa.pojo.UserLoginInfo;
import com.oliveoa.pojo.WorkDetail;
import com.oliveoa.pojo.FulltimeApplication;
import com.oliveoa.pojo.FulltimeApplicationApprovedOpinion;
import com.oliveoa.pojo.IssueWorkMember;
import com.oliveoa.pojo.JobTransferApplication;
import com.oliveoa.pojo.JobTransferApplicationApprovedOpinion;
import com.oliveoa.pojo.LeaveOfficeApplication;
import com.oliveoa.pojo.LeaveOfficeApplicationApprovedOpinion;
import com.oliveoa.pojo.MeetingApplication;
import com.oliveoa.pojo.MeetingMember;
import com.oliveoa.pojo.RecruitmentApplicationApprovedOpinion;
import com.oliveoa.pojo.RecruitmentApplicationItem;
import com.oliveoa.pojo.SubmitWork;
import com.oliveoa.pojo.ApproveNumber;
import com.oliveoa.pojo.DepartmentAndDuty;
import com.oliveoa.pojo.MeetingApplicationAndStatus;
import com.oliveoa.pojo.NoteInfo;
import com.oliveoa.pojo.UserInfo;

import com.oliveoa.greendao.AnnouncementApprovedOpinionListDao;
import com.oliveoa.greendao.AnnouncementInfoDao;
import com.oliveoa.greendao.ApplicationDao;
import com.oliveoa.greendao.BusinessTripApplicationDao;
import com.oliveoa.greendao.BusinessTripApplicationApprovedOpinionListDao;
import com.oliveoa.greendao.ContactInfoDao;
import com.oliveoa.greendao.DepartmentInfoDao;
import com.oliveoa.greendao.DutyInfoDao;
import com.oliveoa.greendao.IssueWorkDao;
import com.oliveoa.greendao.LeaveApplicationDao;
import com.oliveoa.greendao.LeaveApplicationApprovedOpinionListDao;
import com.oliveoa.greendao.MessageDao;
import com.oliveoa.greendao.OvertimeApplicationDao;
import com.oliveoa.greendao.OvertimeApplicationApprovedOpinionListDao;
import com.oliveoa.greendao.UserLoginInfoDao;
import com.oliveoa.greendao.WorkDetailDao;
import com.oliveoa.greendao.FulltimeApplicationDao;
import com.oliveoa.greendao.FulltimeApplicationApprovedOpinionDao;
import com.oliveoa.greendao.IssueWorkMemberDao;
import com.oliveoa.greendao.JobTransferApplicationDao;
import com.oliveoa.greendao.JobTransferApplicationApprovedOpinionDao;
import com.oliveoa.greendao.LeaveOfficeApplicationDao;
import com.oliveoa.greendao.LeaveOfficeApplicationApprovedOpinionDao;
import com.oliveoa.greendao.MeetingApplicationDao;
import com.oliveoa.greendao.MeetingMemberDao;
import com.oliveoa.greendao.RecruitmentApplicationApprovedOpinionDao;
import com.oliveoa.greendao.RecruitmentApplicationItemDao;
import com.oliveoa.greendao.SubmitWorkDao;
import com.oliveoa.greendao.ApproveNumberDao;
import com.oliveoa.greendao.DepartmentAndDutyDao;
import com.oliveoa.greendao.MeetingApplicationAndStatusDao;
import com.oliveoa.greendao.NoteInfoDao;
import com.oliveoa.greendao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig announcementApprovedOpinionListDaoConfig;
    private final DaoConfig announcementInfoDaoConfig;
    private final DaoConfig applicationDaoConfig;
    private final DaoConfig businessTripApplicationDaoConfig;
    private final DaoConfig businessTripApplicationApprovedOpinionListDaoConfig;
    private final DaoConfig contactInfoDaoConfig;
    private final DaoConfig departmentInfoDaoConfig;
    private final DaoConfig dutyInfoDaoConfig;
    private final DaoConfig issueWorkDaoConfig;
    private final DaoConfig leaveApplicationDaoConfig;
    private final DaoConfig leaveApplicationApprovedOpinionListDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig overtimeApplicationDaoConfig;
    private final DaoConfig overtimeApplicationApprovedOpinionListDaoConfig;
    private final DaoConfig userLoginInfoDaoConfig;
    private final DaoConfig workDetailDaoConfig;
    private final DaoConfig fulltimeApplicationDaoConfig;
    private final DaoConfig fulltimeApplicationApprovedOpinionDaoConfig;
    private final DaoConfig issueWorkMemberDaoConfig;
    private final DaoConfig jobTransferApplicationDaoConfig;
    private final DaoConfig jobTransferApplicationApprovedOpinionDaoConfig;
    private final DaoConfig leaveOfficeApplicationDaoConfig;
    private final DaoConfig leaveOfficeApplicationApprovedOpinionDaoConfig;
    private final DaoConfig meetingApplicationDaoConfig;
    private final DaoConfig meetingMemberDaoConfig;
    private final DaoConfig recruitmentApplicationApprovedOpinionDaoConfig;
    private final DaoConfig recruitmentApplicationItemDaoConfig;
    private final DaoConfig submitWorkDaoConfig;
    private final DaoConfig approveNumberDaoConfig;
    private final DaoConfig departmentAndDutyDaoConfig;
    private final DaoConfig meetingApplicationAndStatusDaoConfig;
    private final DaoConfig noteInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final AnnouncementApprovedOpinionListDao announcementApprovedOpinionListDao;
    private final AnnouncementInfoDao announcementInfoDao;
    private final ApplicationDao applicationDao;
    private final BusinessTripApplicationDao businessTripApplicationDao;
    private final BusinessTripApplicationApprovedOpinionListDao businessTripApplicationApprovedOpinionListDao;
    private final ContactInfoDao contactInfoDao;
    private final DepartmentInfoDao departmentInfoDao;
    private final DutyInfoDao dutyInfoDao;
    private final IssueWorkDao issueWorkDao;
    private final LeaveApplicationDao leaveApplicationDao;
    private final LeaveApplicationApprovedOpinionListDao leaveApplicationApprovedOpinionListDao;
    private final MessageDao messageDao;
    private final OvertimeApplicationDao overtimeApplicationDao;
    private final OvertimeApplicationApprovedOpinionListDao overtimeApplicationApprovedOpinionListDao;
    private final UserLoginInfoDao userLoginInfoDao;
    private final WorkDetailDao workDetailDao;
    private final FulltimeApplicationDao fulltimeApplicationDao;
    private final FulltimeApplicationApprovedOpinionDao fulltimeApplicationApprovedOpinionDao;
    private final IssueWorkMemberDao issueWorkMemberDao;
    private final JobTransferApplicationDao jobTransferApplicationDao;
    private final JobTransferApplicationApprovedOpinionDao jobTransferApplicationApprovedOpinionDao;
    private final LeaveOfficeApplicationDao leaveOfficeApplicationDao;
    private final LeaveOfficeApplicationApprovedOpinionDao leaveOfficeApplicationApprovedOpinionDao;
    private final MeetingApplicationDao meetingApplicationDao;
    private final MeetingMemberDao meetingMemberDao;
    private final RecruitmentApplicationApprovedOpinionDao recruitmentApplicationApprovedOpinionDao;
    private final RecruitmentApplicationItemDao recruitmentApplicationItemDao;
    private final SubmitWorkDao submitWorkDao;
    private final ApproveNumberDao approveNumberDao;
    private final DepartmentAndDutyDao departmentAndDutyDao;
    private final MeetingApplicationAndStatusDao meetingApplicationAndStatusDao;
    private final NoteInfoDao noteInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        announcementApprovedOpinionListDaoConfig = daoConfigMap.get(AnnouncementApprovedOpinionListDao.class).clone();
        announcementApprovedOpinionListDaoConfig.initIdentityScope(type);

        announcementInfoDaoConfig = daoConfigMap.get(AnnouncementInfoDao.class).clone();
        announcementInfoDaoConfig.initIdentityScope(type);

        applicationDaoConfig = daoConfigMap.get(ApplicationDao.class).clone();
        applicationDaoConfig.initIdentityScope(type);

        businessTripApplicationDaoConfig = daoConfigMap.get(BusinessTripApplicationDao.class).clone();
        businessTripApplicationDaoConfig.initIdentityScope(type);

        businessTripApplicationApprovedOpinionListDaoConfig = daoConfigMap.get(BusinessTripApplicationApprovedOpinionListDao.class).clone();
        businessTripApplicationApprovedOpinionListDaoConfig.initIdentityScope(type);

        contactInfoDaoConfig = daoConfigMap.get(ContactInfoDao.class).clone();
        contactInfoDaoConfig.initIdentityScope(type);

        departmentInfoDaoConfig = daoConfigMap.get(DepartmentInfoDao.class).clone();
        departmentInfoDaoConfig.initIdentityScope(type);

        dutyInfoDaoConfig = daoConfigMap.get(DutyInfoDao.class).clone();
        dutyInfoDaoConfig.initIdentityScope(type);

        issueWorkDaoConfig = daoConfigMap.get(IssueWorkDao.class).clone();
        issueWorkDaoConfig.initIdentityScope(type);

        leaveApplicationDaoConfig = daoConfigMap.get(LeaveApplicationDao.class).clone();
        leaveApplicationDaoConfig.initIdentityScope(type);

        leaveApplicationApprovedOpinionListDaoConfig = daoConfigMap.get(LeaveApplicationApprovedOpinionListDao.class).clone();
        leaveApplicationApprovedOpinionListDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        overtimeApplicationDaoConfig = daoConfigMap.get(OvertimeApplicationDao.class).clone();
        overtimeApplicationDaoConfig.initIdentityScope(type);

        overtimeApplicationApprovedOpinionListDaoConfig = daoConfigMap.get(OvertimeApplicationApprovedOpinionListDao.class).clone();
        overtimeApplicationApprovedOpinionListDaoConfig.initIdentityScope(type);

        userLoginInfoDaoConfig = daoConfigMap.get(UserLoginInfoDao.class).clone();
        userLoginInfoDaoConfig.initIdentityScope(type);

        workDetailDaoConfig = daoConfigMap.get(WorkDetailDao.class).clone();
        workDetailDaoConfig.initIdentityScope(type);

        fulltimeApplicationDaoConfig = daoConfigMap.get(FulltimeApplicationDao.class).clone();
        fulltimeApplicationDaoConfig.initIdentityScope(type);

        fulltimeApplicationApprovedOpinionDaoConfig = daoConfigMap.get(FulltimeApplicationApprovedOpinionDao.class).clone();
        fulltimeApplicationApprovedOpinionDaoConfig.initIdentityScope(type);

        issueWorkMemberDaoConfig = daoConfigMap.get(IssueWorkMemberDao.class).clone();
        issueWorkMemberDaoConfig.initIdentityScope(type);

        jobTransferApplicationDaoConfig = daoConfigMap.get(JobTransferApplicationDao.class).clone();
        jobTransferApplicationDaoConfig.initIdentityScope(type);

        jobTransferApplicationApprovedOpinionDaoConfig = daoConfigMap.get(JobTransferApplicationApprovedOpinionDao.class).clone();
        jobTransferApplicationApprovedOpinionDaoConfig.initIdentityScope(type);

        leaveOfficeApplicationDaoConfig = daoConfigMap.get(LeaveOfficeApplicationDao.class).clone();
        leaveOfficeApplicationDaoConfig.initIdentityScope(type);

        leaveOfficeApplicationApprovedOpinionDaoConfig = daoConfigMap.get(LeaveOfficeApplicationApprovedOpinionDao.class).clone();
        leaveOfficeApplicationApprovedOpinionDaoConfig.initIdentityScope(type);

        meetingApplicationDaoConfig = daoConfigMap.get(MeetingApplicationDao.class).clone();
        meetingApplicationDaoConfig.initIdentityScope(type);

        meetingMemberDaoConfig = daoConfigMap.get(MeetingMemberDao.class).clone();
        meetingMemberDaoConfig.initIdentityScope(type);

        recruitmentApplicationApprovedOpinionDaoConfig = daoConfigMap.get(RecruitmentApplicationApprovedOpinionDao.class).clone();
        recruitmentApplicationApprovedOpinionDaoConfig.initIdentityScope(type);

        recruitmentApplicationItemDaoConfig = daoConfigMap.get(RecruitmentApplicationItemDao.class).clone();
        recruitmentApplicationItemDaoConfig.initIdentityScope(type);

        submitWorkDaoConfig = daoConfigMap.get(SubmitWorkDao.class).clone();
        submitWorkDaoConfig.initIdentityScope(type);

        approveNumberDaoConfig = daoConfigMap.get(ApproveNumberDao.class).clone();
        approveNumberDaoConfig.initIdentityScope(type);

        departmentAndDutyDaoConfig = daoConfigMap.get(DepartmentAndDutyDao.class).clone();
        departmentAndDutyDaoConfig.initIdentityScope(type);

        meetingApplicationAndStatusDaoConfig = daoConfigMap.get(MeetingApplicationAndStatusDao.class).clone();
        meetingApplicationAndStatusDaoConfig.initIdentityScope(type);

        noteInfoDaoConfig = daoConfigMap.get(NoteInfoDao.class).clone();
        noteInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        announcementApprovedOpinionListDao = new AnnouncementApprovedOpinionListDao(announcementApprovedOpinionListDaoConfig, this);
        announcementInfoDao = new AnnouncementInfoDao(announcementInfoDaoConfig, this);
        applicationDao = new ApplicationDao(applicationDaoConfig, this);
        businessTripApplicationDao = new BusinessTripApplicationDao(businessTripApplicationDaoConfig, this);
        businessTripApplicationApprovedOpinionListDao = new BusinessTripApplicationApprovedOpinionListDao(businessTripApplicationApprovedOpinionListDaoConfig, this);
        contactInfoDao = new ContactInfoDao(contactInfoDaoConfig, this);
        departmentInfoDao = new DepartmentInfoDao(departmentInfoDaoConfig, this);
        dutyInfoDao = new DutyInfoDao(dutyInfoDaoConfig, this);
        issueWorkDao = new IssueWorkDao(issueWorkDaoConfig, this);
        leaveApplicationDao = new LeaveApplicationDao(leaveApplicationDaoConfig, this);
        leaveApplicationApprovedOpinionListDao = new LeaveApplicationApprovedOpinionListDao(leaveApplicationApprovedOpinionListDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        overtimeApplicationDao = new OvertimeApplicationDao(overtimeApplicationDaoConfig, this);
        overtimeApplicationApprovedOpinionListDao = new OvertimeApplicationApprovedOpinionListDao(overtimeApplicationApprovedOpinionListDaoConfig, this);
        userLoginInfoDao = new UserLoginInfoDao(userLoginInfoDaoConfig, this);
        workDetailDao = new WorkDetailDao(workDetailDaoConfig, this);
        fulltimeApplicationDao = new FulltimeApplicationDao(fulltimeApplicationDaoConfig, this);
        fulltimeApplicationApprovedOpinionDao = new FulltimeApplicationApprovedOpinionDao(fulltimeApplicationApprovedOpinionDaoConfig, this);
        issueWorkMemberDao = new IssueWorkMemberDao(issueWorkMemberDaoConfig, this);
        jobTransferApplicationDao = new JobTransferApplicationDao(jobTransferApplicationDaoConfig, this);
        jobTransferApplicationApprovedOpinionDao = new JobTransferApplicationApprovedOpinionDao(jobTransferApplicationApprovedOpinionDaoConfig, this);
        leaveOfficeApplicationDao = new LeaveOfficeApplicationDao(leaveOfficeApplicationDaoConfig, this);
        leaveOfficeApplicationApprovedOpinionDao = new LeaveOfficeApplicationApprovedOpinionDao(leaveOfficeApplicationApprovedOpinionDaoConfig, this);
        meetingApplicationDao = new MeetingApplicationDao(meetingApplicationDaoConfig, this);
        meetingMemberDao = new MeetingMemberDao(meetingMemberDaoConfig, this);
        recruitmentApplicationApprovedOpinionDao = new RecruitmentApplicationApprovedOpinionDao(recruitmentApplicationApprovedOpinionDaoConfig, this);
        recruitmentApplicationItemDao = new RecruitmentApplicationItemDao(recruitmentApplicationItemDaoConfig, this);
        submitWorkDao = new SubmitWorkDao(submitWorkDaoConfig, this);
        approveNumberDao = new ApproveNumberDao(approveNumberDaoConfig, this);
        departmentAndDutyDao = new DepartmentAndDutyDao(departmentAndDutyDaoConfig, this);
        meetingApplicationAndStatusDao = new MeetingApplicationAndStatusDao(meetingApplicationAndStatusDaoConfig, this);
        noteInfoDao = new NoteInfoDao(noteInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(AnnouncementApprovedOpinionList.class, announcementApprovedOpinionListDao);
        registerDao(AnnouncementInfo.class, announcementInfoDao);
        registerDao(Application.class, applicationDao);
        registerDao(BusinessTripApplication.class, businessTripApplicationDao);
        registerDao(BusinessTripApplicationApprovedOpinionList.class, businessTripApplicationApprovedOpinionListDao);
        registerDao(ContactInfo.class, contactInfoDao);
        registerDao(DepartmentInfo.class, departmentInfoDao);
        registerDao(DutyInfo.class, dutyInfoDao);
        registerDao(IssueWork.class, issueWorkDao);
        registerDao(LeaveApplication.class, leaveApplicationDao);
        registerDao(LeaveApplicationApprovedOpinionList.class, leaveApplicationApprovedOpinionListDao);
        registerDao(Message.class, messageDao);
        registerDao(OvertimeApplication.class, overtimeApplicationDao);
        registerDao(OvertimeApplicationApprovedOpinionList.class, overtimeApplicationApprovedOpinionListDao);
        registerDao(UserLoginInfo.class, userLoginInfoDao);
        registerDao(WorkDetail.class, workDetailDao);
        registerDao(FulltimeApplication.class, fulltimeApplicationDao);
        registerDao(FulltimeApplicationApprovedOpinion.class, fulltimeApplicationApprovedOpinionDao);
        registerDao(IssueWorkMember.class, issueWorkMemberDao);
        registerDao(JobTransferApplication.class, jobTransferApplicationDao);
        registerDao(JobTransferApplicationApprovedOpinion.class, jobTransferApplicationApprovedOpinionDao);
        registerDao(LeaveOfficeApplication.class, leaveOfficeApplicationDao);
        registerDao(LeaveOfficeApplicationApprovedOpinion.class, leaveOfficeApplicationApprovedOpinionDao);
        registerDao(MeetingApplication.class, meetingApplicationDao);
        registerDao(MeetingMember.class, meetingMemberDao);
        registerDao(RecruitmentApplicationApprovedOpinion.class, recruitmentApplicationApprovedOpinionDao);
        registerDao(RecruitmentApplicationItem.class, recruitmentApplicationItemDao);
        registerDao(SubmitWork.class, submitWorkDao);
        registerDao(ApproveNumber.class, approveNumberDao);
        registerDao(DepartmentAndDuty.class, departmentAndDutyDao);
        registerDao(MeetingApplicationAndStatus.class, meetingApplicationAndStatusDao);
        registerDao(NoteInfo.class, noteInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        announcementApprovedOpinionListDaoConfig.clearIdentityScope();
        announcementInfoDaoConfig.clearIdentityScope();
        applicationDaoConfig.clearIdentityScope();
        businessTripApplicationDaoConfig.clearIdentityScope();
        businessTripApplicationApprovedOpinionListDaoConfig.clearIdentityScope();
        contactInfoDaoConfig.clearIdentityScope();
        departmentInfoDaoConfig.clearIdentityScope();
        dutyInfoDaoConfig.clearIdentityScope();
        issueWorkDaoConfig.clearIdentityScope();
        leaveApplicationDaoConfig.clearIdentityScope();
        leaveApplicationApprovedOpinionListDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        overtimeApplicationDaoConfig.clearIdentityScope();
        overtimeApplicationApprovedOpinionListDaoConfig.clearIdentityScope();
        userLoginInfoDaoConfig.clearIdentityScope();
        workDetailDaoConfig.clearIdentityScope();
        fulltimeApplicationDaoConfig.clearIdentityScope();
        fulltimeApplicationApprovedOpinionDaoConfig.clearIdentityScope();
        issueWorkMemberDaoConfig.clearIdentityScope();
        jobTransferApplicationDaoConfig.clearIdentityScope();
        jobTransferApplicationApprovedOpinionDaoConfig.clearIdentityScope();
        leaveOfficeApplicationDaoConfig.clearIdentityScope();
        leaveOfficeApplicationApprovedOpinionDaoConfig.clearIdentityScope();
        meetingApplicationDaoConfig.clearIdentityScope();
        meetingMemberDaoConfig.clearIdentityScope();
        recruitmentApplicationApprovedOpinionDaoConfig.clearIdentityScope();
        recruitmentApplicationItemDaoConfig.clearIdentityScope();
        submitWorkDaoConfig.clearIdentityScope();
        approveNumberDaoConfig.clearIdentityScope();
        departmentAndDutyDaoConfig.clearIdentityScope();
        meetingApplicationAndStatusDaoConfig.clearIdentityScope();
        noteInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public AnnouncementApprovedOpinionListDao getAnnouncementApprovedOpinionListDao() {
        return announcementApprovedOpinionListDao;
    }

    public AnnouncementInfoDao getAnnouncementInfoDao() {
        return announcementInfoDao;
    }

    public ApplicationDao getApplicationDao() {
        return applicationDao;
    }

    public BusinessTripApplicationDao getBusinessTripApplicationDao() {
        return businessTripApplicationDao;
    }

    public BusinessTripApplicationApprovedOpinionListDao getBusinessTripApplicationApprovedOpinionListDao() {
        return businessTripApplicationApprovedOpinionListDao;
    }

    public ContactInfoDao getContactInfoDao() {
        return contactInfoDao;
    }

    public DepartmentInfoDao getDepartmentInfoDao() {
        return departmentInfoDao;
    }

    public DutyInfoDao getDutyInfoDao() {
        return dutyInfoDao;
    }

    public IssueWorkDao getIssueWorkDao() {
        return issueWorkDao;
    }

    public LeaveApplicationDao getLeaveApplicationDao() {
        return leaveApplicationDao;
    }

    public LeaveApplicationApprovedOpinionListDao getLeaveApplicationApprovedOpinionListDao() {
        return leaveApplicationApprovedOpinionListDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public OvertimeApplicationDao getOvertimeApplicationDao() {
        return overtimeApplicationDao;
    }

    public OvertimeApplicationApprovedOpinionListDao getOvertimeApplicationApprovedOpinionListDao() {
        return overtimeApplicationApprovedOpinionListDao;
    }

    public UserLoginInfoDao getUserLoginInfoDao() {
        return userLoginInfoDao;
    }

    public WorkDetailDao getWorkDetailDao() {
        return workDetailDao;
    }

    public FulltimeApplicationDao getFulltimeApplicationDao() {
        return fulltimeApplicationDao;
    }

    public FulltimeApplicationApprovedOpinionDao getFulltimeApplicationApprovedOpinionDao() {
        return fulltimeApplicationApprovedOpinionDao;
    }

    public IssueWorkMemberDao getIssueWorkMemberDao() {
        return issueWorkMemberDao;
    }

    public JobTransferApplicationDao getJobTransferApplicationDao() {
        return jobTransferApplicationDao;
    }

    public JobTransferApplicationApprovedOpinionDao getJobTransferApplicationApprovedOpinionDao() {
        return jobTransferApplicationApprovedOpinionDao;
    }

    public LeaveOfficeApplicationDao getLeaveOfficeApplicationDao() {
        return leaveOfficeApplicationDao;
    }

    public LeaveOfficeApplicationApprovedOpinionDao getLeaveOfficeApplicationApprovedOpinionDao() {
        return leaveOfficeApplicationApprovedOpinionDao;
    }

    public MeetingApplicationDao getMeetingApplicationDao() {
        return meetingApplicationDao;
    }

    public MeetingMemberDao getMeetingMemberDao() {
        return meetingMemberDao;
    }

    public RecruitmentApplicationApprovedOpinionDao getRecruitmentApplicationApprovedOpinionDao() {
        return recruitmentApplicationApprovedOpinionDao;
    }

    public RecruitmentApplicationItemDao getRecruitmentApplicationItemDao() {
        return recruitmentApplicationItemDao;
    }

    public SubmitWorkDao getSubmitWorkDao() {
        return submitWorkDao;
    }

    public ApproveNumberDao getApproveNumberDao() {
        return approveNumberDao;
    }

    public DepartmentAndDutyDao getDepartmentAndDutyDao() {
        return departmentAndDutyDao;
    }

    public MeetingApplicationAndStatusDao getMeetingApplicationAndStatusDao() {
        return meetingApplicationAndStatusDao;
    }

    public NoteInfoDao getNoteInfoDao() {
        return noteInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
