package com.oliveoa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oliveoa.pojo.DutyInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DUTY_INFO".
*/
public class DutyInfoDao extends AbstractDao<DutyInfo, Void> {

    public static final String TABLENAME = "DUTY_INFO";

    /**
     * Properties of entity DutyInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Pcid = new Property(0, String.class, "pcid", false, "PCID");
        public final static Property Ppid = new Property(1, String.class, "ppid", false, "PPID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Dcid = new Property(3, String.class, "dcid", false, "DCID");
        public final static Property Limit = new Property(4, int.class, "limit", false, "LIMIT");
        public final static Property Orderby = new Property(5, int.class, "orderby", false, "ORDERBY");
        public final static Property Createtime = new Property(6, long.class, "createtime", false, "CREATETIME");
        public final static Property Updatetime = new Property(7, long.class, "updatetime", false, "UPDATETIME");
    }


    public DutyInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DutyInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DUTY_INFO\" (" + //
                "\"PCID\" TEXT," + // 0: pcid
                "\"PPID\" TEXT," + // 1: ppid
                "\"NAME\" TEXT," + // 2: name
                "\"DCID\" TEXT," + // 3: dcid
                "\"LIMIT\" INTEGER NOT NULL ," + // 4: limit
                "\"ORDERBY\" INTEGER NOT NULL ," + // 5: orderby
                "\"CREATETIME\" INTEGER NOT NULL ," + // 6: createtime
                "\"UPDATETIME\" INTEGER NOT NULL );"); // 7: updatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DUTY_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DutyInfo entity) {
        stmt.clearBindings();
 
        String pcid = entity.getPcid();
        if (pcid != null) {
            stmt.bindString(1, pcid);
        }
 
        String ppid = entity.getPpid();
        if (ppid != null) {
            stmt.bindString(2, ppid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String dcid = entity.getDcid();
        if (dcid != null) {
            stmt.bindString(4, dcid);
        }
        stmt.bindLong(5, entity.getLimit());
        stmt.bindLong(6, entity.getOrderby());
        stmt.bindLong(7, entity.getCreatetime());
        stmt.bindLong(8, entity.getUpdatetime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DutyInfo entity) {
        stmt.clearBindings();
 
        String pcid = entity.getPcid();
        if (pcid != null) {
            stmt.bindString(1, pcid);
        }
 
        String ppid = entity.getPpid();
        if (ppid != null) {
            stmt.bindString(2, ppid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String dcid = entity.getDcid();
        if (dcid != null) {
            stmt.bindString(4, dcid);
        }
        stmt.bindLong(5, entity.getLimit());
        stmt.bindLong(6, entity.getOrderby());
        stmt.bindLong(7, entity.getCreatetime());
        stmt.bindLong(8, entity.getUpdatetime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public DutyInfo readEntity(Cursor cursor, int offset) {
        DutyInfo entity = new DutyInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // pcid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ppid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // dcid
            cursor.getInt(offset + 4), // limit
            cursor.getInt(offset + 5), // orderby
            cursor.getLong(offset + 6), // createtime
            cursor.getLong(offset + 7) // updatetime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DutyInfo entity, int offset) {
        entity.setPcid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPpid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDcid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLimit(cursor.getInt(offset + 4));
        entity.setOrderby(cursor.getInt(offset + 5));
        entity.setCreatetime(cursor.getLong(offset + 6));
        entity.setUpdatetime(cursor.getLong(offset + 7));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(DutyInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(DutyInfo entity) {
        return null;
    }

    @Override
    public boolean hasKey(DutyInfo entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
