package com.oliveoa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oliveoa.pojo.LeaveOfficeApplicationApprovedOpinion;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LEAVE_OFFICE_APPLICATION_APPROVED_OPINION".
*/
public class LeaveOfficeApplicationApprovedOpinionDao extends AbstractDao<LeaveOfficeApplicationApprovedOpinion, Void> {

    public static final String TABLENAME = "LEAVE_OFFICE_APPLICATION_APPROVED_OPINION";

    /**
     * Properties of entity LeaveOfficeApplicationApprovedOpinion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Loaaocid = new Property(0, String.class, "loaaocid", false, "LOAAOCID");
        public final static Property Loaaopid = new Property(1, String.class, "loaaopid", false, "LOAAOPID");
        public final static Property Loaid = new Property(2, String.class, "loaid", false, "LOAID");
        public final static Property Eid = new Property(3, String.class, "eid", false, "EID");
        public final static Property Isapproved = new Property(4, Integer.class, "isapproved", false, "ISAPPROVED");
        public final static Property Opinion = new Property(5, String.class, "opinion", false, "OPINION");
        public final static Property Orderby = new Property(6, Integer.class, "orderby", false, "ORDERBY");
        public final static Property Createtime = new Property(7, long.class, "createtime", false, "CREATETIME");
        public final static Property Updatetime = new Property(8, long.class, "updatetime", false, "UPDATETIME");
    }


    public LeaveOfficeApplicationApprovedOpinionDao(DaoConfig config) {
        super(config);
    }
    
    public LeaveOfficeApplicationApprovedOpinionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LEAVE_OFFICE_APPLICATION_APPROVED_OPINION\" (" + //
                "\"LOAAOCID\" TEXT," + // 0: loaaocid
                "\"LOAAOPID\" TEXT," + // 1: loaaopid
                "\"LOAID\" TEXT," + // 2: loaid
                "\"EID\" TEXT," + // 3: eid
                "\"ISAPPROVED\" INTEGER," + // 4: isapproved
                "\"OPINION\" TEXT," + // 5: opinion
                "\"ORDERBY\" INTEGER," + // 6: orderby
                "\"CREATETIME\" INTEGER NOT NULL ," + // 7: createtime
                "\"UPDATETIME\" INTEGER NOT NULL );"); // 8: updatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LEAVE_OFFICE_APPLICATION_APPROVED_OPINION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LeaveOfficeApplicationApprovedOpinion entity) {
        stmt.clearBindings();
 
        String loaaocid = entity.getLoaaocid();
        if (loaaocid != null) {
            stmt.bindString(1, loaaocid);
        }
 
        String loaaopid = entity.getLoaaopid();
        if (loaaopid != null) {
            stmt.bindString(2, loaaopid);
        }
 
        String loaid = entity.getLoaid();
        if (loaid != null) {
            stmt.bindString(3, loaid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(4, eid);
        }
 
        Integer isapproved = entity.getIsapproved();
        if (isapproved != null) {
            stmt.bindLong(5, isapproved);
        }
 
        String opinion = entity.getOpinion();
        if (opinion != null) {
            stmt.bindString(6, opinion);
        }
 
        Integer orderby = entity.getOrderby();
        if (orderby != null) {
            stmt.bindLong(7, orderby);
        }
        stmt.bindLong(8, entity.getCreatetime());
        stmt.bindLong(9, entity.getUpdatetime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LeaveOfficeApplicationApprovedOpinion entity) {
        stmt.clearBindings();
 
        String loaaocid = entity.getLoaaocid();
        if (loaaocid != null) {
            stmt.bindString(1, loaaocid);
        }
 
        String loaaopid = entity.getLoaaopid();
        if (loaaopid != null) {
            stmt.bindString(2, loaaopid);
        }
 
        String loaid = entity.getLoaid();
        if (loaid != null) {
            stmt.bindString(3, loaid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(4, eid);
        }
 
        Integer isapproved = entity.getIsapproved();
        if (isapproved != null) {
            stmt.bindLong(5, isapproved);
        }
 
        String opinion = entity.getOpinion();
        if (opinion != null) {
            stmt.bindString(6, opinion);
        }
 
        Integer orderby = entity.getOrderby();
        if (orderby != null) {
            stmt.bindLong(7, orderby);
        }
        stmt.bindLong(8, entity.getCreatetime());
        stmt.bindLong(9, entity.getUpdatetime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public LeaveOfficeApplicationApprovedOpinion readEntity(Cursor cursor, int offset) {
        LeaveOfficeApplicationApprovedOpinion entity = new LeaveOfficeApplicationApprovedOpinion( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // loaaocid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // loaaopid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // loaid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // eid
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // isapproved
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // opinion
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // orderby
            cursor.getLong(offset + 7), // createtime
            cursor.getLong(offset + 8) // updatetime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LeaveOfficeApplicationApprovedOpinion entity, int offset) {
        entity.setLoaaocid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLoaaopid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLoaid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsapproved(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setOpinion(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOrderby(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setCreatetime(cursor.getLong(offset + 7));
        entity.setUpdatetime(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(LeaveOfficeApplicationApprovedOpinion entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(LeaveOfficeApplicationApprovedOpinion entity) {
        return null;
    }

    @Override
    public boolean hasKey(LeaveOfficeApplicationApprovedOpinion entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
