package com.oliveoa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oliveoa.pojo.MeetingApplication;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEETING_APPLICATION".
*/
public class MeetingApplicationDao extends AbstractDao<MeetingApplication, Void> {

    public static final String TABLENAME = "MEETING_APPLICATION";

    /**
     * Properties of entity MeetingApplication.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Maid = new Property(0, String.class, "maid", false, "MAID");
        public final static Property Eid = new Property(1, String.class, "eid", false, "EID");
        public final static Property Aeid = new Property(2, String.class, "aeid", false, "AEID");
        public final static Property Theme = new Property(3, String.class, "theme", false, "THEME");
        public final static Property Begintime = new Property(4, long.class, "begintime", false, "BEGINTIME");
        public final static Property Endtime = new Property(5, long.class, "endtime", false, "ENDTIME");
        public final static Property Place = new Property(6, String.class, "place", false, "PLACE");
        public final static Property Isapproved = new Property(7, Integer.class, "isapproved", false, "ISAPPROVED");
        public final static Property Opinion = new Property(8, String.class, "opinion", false, "OPINION");
        public final static Property Orderby = new Property(9, Integer.class, "orderby", false, "ORDERBY");
        public final static Property Updatetime = new Property(10, long.class, "updatetime", false, "UPDATETIME");
        public final static Property Createtime = new Property(11, long.class, "createtime", false, "CREATETIME");
    }


    public MeetingApplicationDao(DaoConfig config) {
        super(config);
    }
    
    public MeetingApplicationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEETING_APPLICATION\" (" + //
                "\"MAID\" TEXT," + // 0: maid
                "\"EID\" TEXT," + // 1: eid
                "\"AEID\" TEXT," + // 2: aeid
                "\"THEME\" TEXT," + // 3: theme
                "\"BEGINTIME\" INTEGER NOT NULL ," + // 4: begintime
                "\"ENDTIME\" INTEGER NOT NULL ," + // 5: endtime
                "\"PLACE\" TEXT," + // 6: place
                "\"ISAPPROVED\" INTEGER," + // 7: isapproved
                "\"OPINION\" TEXT," + // 8: opinion
                "\"ORDERBY\" INTEGER," + // 9: orderby
                "\"UPDATETIME\" INTEGER NOT NULL ," + // 10: updatetime
                "\"CREATETIME\" INTEGER NOT NULL );"); // 11: createtime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEETING_APPLICATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MeetingApplication entity) {
        stmt.clearBindings();
 
        String maid = entity.getMaid();
        if (maid != null) {
            stmt.bindString(1, maid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(2, eid);
        }
 
        String aeid = entity.getAeid();
        if (aeid != null) {
            stmt.bindString(3, aeid);
        }
 
        String theme = entity.getTheme();
        if (theme != null) {
            stmt.bindString(4, theme);
        }
        stmt.bindLong(5, entity.getBegintime());
        stmt.bindLong(6, entity.getEndtime());
 
        String place = entity.getPlace();
        if (place != null) {
            stmt.bindString(7, place);
        }
 
        Integer isapproved = entity.getIsapproved();
        if (isapproved != null) {
            stmt.bindLong(8, isapproved);
        }
 
        String opinion = entity.getOpinion();
        if (opinion != null) {
            stmt.bindString(9, opinion);
        }
 
        Integer orderby = entity.getOrderby();
        if (orderby != null) {
            stmt.bindLong(10, orderby);
        }
        stmt.bindLong(11, entity.getUpdatetime());
        stmt.bindLong(12, entity.getCreatetime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MeetingApplication entity) {
        stmt.clearBindings();
 
        String maid = entity.getMaid();
        if (maid != null) {
            stmt.bindString(1, maid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(2, eid);
        }
 
        String aeid = entity.getAeid();
        if (aeid != null) {
            stmt.bindString(3, aeid);
        }
 
        String theme = entity.getTheme();
        if (theme != null) {
            stmt.bindString(4, theme);
        }
        stmt.bindLong(5, entity.getBegintime());
        stmt.bindLong(6, entity.getEndtime());
 
        String place = entity.getPlace();
        if (place != null) {
            stmt.bindString(7, place);
        }
 
        Integer isapproved = entity.getIsapproved();
        if (isapproved != null) {
            stmt.bindLong(8, isapproved);
        }
 
        String opinion = entity.getOpinion();
        if (opinion != null) {
            stmt.bindString(9, opinion);
        }
 
        Integer orderby = entity.getOrderby();
        if (orderby != null) {
            stmt.bindLong(10, orderby);
        }
        stmt.bindLong(11, entity.getUpdatetime());
        stmt.bindLong(12, entity.getCreatetime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public MeetingApplication readEntity(Cursor cursor, int offset) {
        MeetingApplication entity = new MeetingApplication( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // maid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // eid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // aeid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // theme
            cursor.getLong(offset + 4), // begintime
            cursor.getLong(offset + 5), // endtime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // place
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // isapproved
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // opinion
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // orderby
            cursor.getLong(offset + 10), // updatetime
            cursor.getLong(offset + 11) // createtime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MeetingApplication entity, int offset) {
        entity.setMaid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setEid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAeid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTheme(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBegintime(cursor.getLong(offset + 4));
        entity.setEndtime(cursor.getLong(offset + 5));
        entity.setPlace(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsapproved(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setOpinion(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setOrderby(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setUpdatetime(cursor.getLong(offset + 10));
        entity.setCreatetime(cursor.getLong(offset + 11));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(MeetingApplication entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(MeetingApplication entity) {
        return null;
    }

    @Override
    public boolean hasKey(MeetingApplication entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
