package com.oliveoa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oliveoa.pojo.OvertimeApplication;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OVERTIME_APPLICATION".
*/
public class OvertimeApplicationDao extends AbstractDao<OvertimeApplication, Void> {

    public static final String TABLENAME = "OVERTIME_APPLICATION";

    /**
     * Properties of entity OvertimeApplication.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Oaid = new Property(0, String.class, "oaid", false, "OAID");
        public final static Property Eid = new Property(1, String.class, "eid", false, "EID");
        public final static Property Reason = new Property(2, String.class, "reason", false, "REASON");
        public final static Property Begintime = new Property(3, long.class, "begintime", false, "BEGINTIME");
        public final static Property Endtime = new Property(4, long.class, "endtime", false, "ENDTIME");
        public final static Property Orderby = new Property(5, int.class, "orderby", false, "ORDERBY");
        public final static Property Createtime = new Property(6, long.class, "createtime", false, "CREATETIME");
        public final static Property Updatetime = new Property(7, long.class, "updatetime", false, "UPDATETIME");
    }


    public OvertimeApplicationDao(DaoConfig config) {
        super(config);
    }
    
    public OvertimeApplicationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OVERTIME_APPLICATION\" (" + //
                "\"OAID\" TEXT," + // 0: oaid
                "\"EID\" TEXT," + // 1: eid
                "\"REASON\" TEXT," + // 2: reason
                "\"BEGINTIME\" INTEGER NOT NULL ," + // 3: begintime
                "\"ENDTIME\" INTEGER NOT NULL ," + // 4: endtime
                "\"ORDERBY\" INTEGER NOT NULL ," + // 5: orderby
                "\"CREATETIME\" INTEGER NOT NULL ," + // 6: createtime
                "\"UPDATETIME\" INTEGER NOT NULL );"); // 7: updatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OVERTIME_APPLICATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OvertimeApplication entity) {
        stmt.clearBindings();
 
        String oaid = entity.getOaid();
        if (oaid != null) {
            stmt.bindString(1, oaid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(2, eid);
        }
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(3, reason);
        }
        stmt.bindLong(4, entity.getBegintime());
        stmt.bindLong(5, entity.getEndtime());
        stmt.bindLong(6, entity.getOrderby());
        stmt.bindLong(7, entity.getCreatetime());
        stmt.bindLong(8, entity.getUpdatetime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OvertimeApplication entity) {
        stmt.clearBindings();
 
        String oaid = entity.getOaid();
        if (oaid != null) {
            stmt.bindString(1, oaid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(2, eid);
        }
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(3, reason);
        }
        stmt.bindLong(4, entity.getBegintime());
        stmt.bindLong(5, entity.getEndtime());
        stmt.bindLong(6, entity.getOrderby());
        stmt.bindLong(7, entity.getCreatetime());
        stmt.bindLong(8, entity.getUpdatetime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public OvertimeApplication readEntity(Cursor cursor, int offset) {
        OvertimeApplication entity = new OvertimeApplication( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // oaid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // eid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // reason
            cursor.getLong(offset + 3), // begintime
            cursor.getLong(offset + 4), // endtime
            cursor.getInt(offset + 5), // orderby
            cursor.getLong(offset + 6), // createtime
            cursor.getLong(offset + 7) // updatetime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OvertimeApplication entity, int offset) {
        entity.setOaid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setEid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setReason(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBegintime(cursor.getLong(offset + 3));
        entity.setEndtime(cursor.getLong(offset + 4));
        entity.setOrderby(cursor.getInt(offset + 5));
        entity.setCreatetime(cursor.getLong(offset + 6));
        entity.setUpdatetime(cursor.getLong(offset + 7));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(OvertimeApplication entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(OvertimeApplication entity) {
        return null;
    }

    @Override
    public boolean hasKey(OvertimeApplication entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
