package com.oliveoa.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oliveoa.pojo.RecruitmentApplicationApprovedOpinion;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECRUITMENT_APPLICATION_APPROVED_OPINION".
*/
public class RecruitmentApplicationApprovedOpinionDao extends AbstractDao<RecruitmentApplicationApprovedOpinion, Void> {

    public static final String TABLENAME = "RECRUITMENT_APPLICATION_APPROVED_OPINION";

    /**
     * Properties of entity RecruitmentApplicationApprovedOpinion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Raaocid = new Property(0, String.class, "raaocid", false, "RAAOCID");
        public final static Property Raaopid = new Property(1, String.class, "raaopid", false, "RAAOPID");
        public final static Property Raid = new Property(2, String.class, "raid", false, "RAID");
        public final static Property Eid = new Property(3, String.class, "eid", false, "EID");
        public final static Property Isapproved = new Property(4, Integer.class, "isapproved", false, "ISAPPROVED");
        public final static Property Opinion = new Property(5, String.class, "opinion", false, "OPINION");
        public final static Property Orderby = new Property(6, Integer.class, "orderby", false, "ORDERBY");
        public final static Property Createtime = new Property(7, long.class, "createtime", false, "CREATETIME");
        public final static Property Updatetime = new Property(8, long.class, "updatetime", false, "UPDATETIME");
    }


    public RecruitmentApplicationApprovedOpinionDao(DaoConfig config) {
        super(config);
    }
    
    public RecruitmentApplicationApprovedOpinionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECRUITMENT_APPLICATION_APPROVED_OPINION\" (" + //
                "\"RAAOCID\" TEXT," + // 0: raaocid
                "\"RAAOPID\" TEXT," + // 1: raaopid
                "\"RAID\" TEXT," + // 2: raid
                "\"EID\" TEXT," + // 3: eid
                "\"ISAPPROVED\" INTEGER," + // 4: isapproved
                "\"OPINION\" TEXT," + // 5: opinion
                "\"ORDERBY\" INTEGER," + // 6: orderby
                "\"CREATETIME\" INTEGER NOT NULL ," + // 7: createtime
                "\"UPDATETIME\" INTEGER NOT NULL );"); // 8: updatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECRUITMENT_APPLICATION_APPROVED_OPINION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RecruitmentApplicationApprovedOpinion entity) {
        stmt.clearBindings();
 
        String raaocid = entity.getRaaocid();
        if (raaocid != null) {
            stmt.bindString(1, raaocid);
        }
 
        String raaopid = entity.getRaaopid();
        if (raaopid != null) {
            stmt.bindString(2, raaopid);
        }
 
        String raid = entity.getRaid();
        if (raid != null) {
            stmt.bindString(3, raid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(4, eid);
        }
 
        Integer isapproved = entity.getIsapproved();
        if (isapproved != null) {
            stmt.bindLong(5, isapproved);
        }
 
        String opinion = entity.getOpinion();
        if (opinion != null) {
            stmt.bindString(6, opinion);
        }
 
        Integer orderby = entity.getOrderby();
        if (orderby != null) {
            stmt.bindLong(7, orderby);
        }
        stmt.bindLong(8, entity.getCreatetime());
        stmt.bindLong(9, entity.getUpdatetime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RecruitmentApplicationApprovedOpinion entity) {
        stmt.clearBindings();
 
        String raaocid = entity.getRaaocid();
        if (raaocid != null) {
            stmt.bindString(1, raaocid);
        }
 
        String raaopid = entity.getRaaopid();
        if (raaopid != null) {
            stmt.bindString(2, raaopid);
        }
 
        String raid = entity.getRaid();
        if (raid != null) {
            stmt.bindString(3, raid);
        }
 
        String eid = entity.getEid();
        if (eid != null) {
            stmt.bindString(4, eid);
        }
 
        Integer isapproved = entity.getIsapproved();
        if (isapproved != null) {
            stmt.bindLong(5, isapproved);
        }
 
        String opinion = entity.getOpinion();
        if (opinion != null) {
            stmt.bindString(6, opinion);
        }
 
        Integer orderby = entity.getOrderby();
        if (orderby != null) {
            stmt.bindLong(7, orderby);
        }
        stmt.bindLong(8, entity.getCreatetime());
        stmt.bindLong(9, entity.getUpdatetime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public RecruitmentApplicationApprovedOpinion readEntity(Cursor cursor, int offset) {
        RecruitmentApplicationApprovedOpinion entity = new RecruitmentApplicationApprovedOpinion( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // raaocid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // raaopid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // raid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // eid
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // isapproved
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // opinion
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // orderby
            cursor.getLong(offset + 7), // createtime
            cursor.getLong(offset + 8) // updatetime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RecruitmentApplicationApprovedOpinion entity, int offset) {
        entity.setRaaocid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setRaaopid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRaid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsapproved(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setOpinion(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOrderby(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setCreatetime(cursor.getLong(offset + 7));
        entity.setUpdatetime(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(RecruitmentApplicationApprovedOpinion entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(RecruitmentApplicationApprovedOpinion entity) {
        return null;
    }

    @Override
    public boolean hasKey(RecruitmentApplicationApprovedOpinion entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
